version: "3.9"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: u466708795_atac
      MYSQL_USER: user_atac
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user_atac
      PMA_PASSWORD: 123123
    ports:
      - "8080:80"